import {NextResponse} from "next/server";
import crypto from "crypto";
import {isAuthed} from "../../../../lib/admin-guard";
import {listClients,saveClients,tokenHash} from "../../../../lib/client-portal";
import {audit} from "../../../../lib/audit";
export async function GET(){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});return NextResponse.json({clients:(await listClients()).map(({tokenHash,...c})=>c)},{headers:{"Cache-Control":"no-store"}})}
export async function POST(req:Request){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>({}));if(typeof b.name!=="string"||b.name.trim().length<2||b.name.length>100||typeof b.project!=="string"||b.project.trim().length<2||b.project.length>100)return NextResponse.json({error:"Name and project required"},{status:400});const all=await listClients();if(all.length>=100)return NextResponse.json({error:"Client limit reached"},{status:400});const code=crypto.randomBytes(24).toString("base64url");const record={id:crypto.randomUUID(),name:b.name.trim(),project:b.project.trim(),status:"Planning",update:"No public update yet.",createdAt:Date.now(),tokenHash:tokenHash(code)};if(!await saveClients([...all,record]))return NextResponse.json({error:"Storage unavailable"},{status:503});await audit("client-created",`Client ${record.id.slice(0,8)} created`);return NextResponse.json({client:{id:record.id,name:record.name,project:record.project,status:record.status,update:record.update},accessCode:code},{headers:{"Cache-Control":"no-store"}})}
export async function PATCH(req:Request){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>({}));if(typeof b.id!=="string"||typeof b.status!=="string"||typeof b.update!=="string"||b.status.length>80||b.update.length>1000)return NextResponse.json({error:"Bad input"},{status:400});const all=await listClients();const c=all.find(x=>x.id===b.id);if(!c)return NextResponse.json({error:"Not found"},{status:404});c.status=b.status;c.update=b.update;if(!await saveClients(all))return NextResponse.json({error:"Storage unavailable"},{status:503});await audit("client-updated",`Client ${c.id.slice(0,8)} status changed`);return NextResponse.json({ok:true})}
export async function DELETE(req:Request){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});const {id}=await req.json().catch(()=>({}));const all=await listClients();const next=all.filter(c=>c.id!==id);if(next.length===all.length)return NextResponse.json({error:"Not found"},{status:404});if(!await saveClients(next))return NextResponse.json({error:"Storage unavailable"},{status:503});await audit("client-deleted",`Client ${String(id).slice(0,8)} deleted`);return NextResponse.json({ok:true})}
