"use client";
import {useEffect,useState} from "react";
type Account={uid:string;email:string;name:string;clientId?:string;disabled?:boolean;createdAt:number};
type Client={id:string;name:string;project:string};
export default function AuthAccounts(){const [accounts,setAccounts]=useState<Account[]>([]),[clients,setClients]=useState<Client[]>([]),[configured,setConfigured]=useState(false),[status,setStatus]=useState(""),[loaded,setLoaded]=useState(false);
 async function refresh(){const r=await fetch("/api/admin/auth-accounts",{cache:"no-store"});const d=await r.json();if(!r.ok){setStatus(d.error||"Cannot load accounts");return}setAccounts(d.accounts);setClients(d.clients);setConfigured(d.configured);setLoaded(true)}useEffect(()=>{refresh()},[]);
 async function link(uid:string,clientId:string){if(clientId&&!confirm("Only link this sign-in after checking the person's identity and matching the right client project. Continue?"))return;const r=await fetch("/api/admin/auth-accounts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({uid,clientId})});const d=await r.json();setStatus(r.ok?clientId?"Account linked to verified client record.":"Account unlinked.":d.error||"Could not update account");await refresh()}
 async function disable(uid:string){if(!confirm("Disable this sign-in and remove its project link? The access-code login is separate."))return;const r=await fetch("/api/admin/auth-accounts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({uid})});const d=await r.json();setStatus(r.ok?"Account disabled.":d.error||"Could not disable account");await refresh()}
 return <><h1>Account sign-ins</h1><p className="page-sub">People may sign up with Google or email, but an account never sees an existing project or Build Credit until you verify the person and link the correct client record. Email/name match alone is not proof.</p>{!configured&&<div className="admin-panel" role="status">Google and email sign-in are not configured yet. Owner-issued access codes still work.</div>}<div className="admin-panel"><h2>Registered accounts</h2>{!loaded?<p>Loading…</p>:accounts.length===0?<p>No sign-ups yet.</p>:accounts.map(a=><div className="content-editor-item" key={a.uid}><b>{a.name} · {a.email}</b><p>{a.disabled?"Disabled":a.clientId?"Linked client record":"Unlinked - no project or credit access"}</p><label className="admin-field"><span>Verified client project</span><select disabled={a.disabled} value={a.clientId||""} onChange={e=>link(a.uid,e.target.value)}><option value="">No link</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} - {c.project}</option>)}</select></label>{!a.disabled&&<button className="admin-btn danger small" onClick={()=>disable(a.uid)}>Disable account</button>}</div>)}</div><p role="status">{status}</p></>}
