"use client";
import {useState} from "react";
import {PDFDocument,StandardFonts,rgb} from "pdf-lib";
const clean=(s:string)=>s.normalize("NFKD").replace(/[^\x20-\x7E]/g,"?");
function lines(s:string,max=84){return clean(s).split("\n").flatMap(paragraph=>{const words=paragraph.split(/\s+/);const out:string[]=[];let line="";for(const word of words){if(!word)continue;if((line+" "+word).length>max){if(line)out.push(line);line=word}else line+=(line?" ":"")+word}out.push(line);return out});}
export default function QuoteDraft(){const [person,setPerson]=useState(""),[scope,setScope]=useState(""),[amount,setAmount]=useState(""),[currency,setCurrency]=useState("INR"),[terms,setTerms]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function download(){setError("");if(!person.trim()||!scope.trim()||!terms.trim()||!/^\d+(\.\d{1,2})?$/.test(amount)||Number(amount)<=0){setError("Add a recipient, scope, price and valid terms before making a draft.");return}setBusy(true);try{
 const pdf=await PDFDocument.create(),page=pdf.addPage([595,842]),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let y=780;
 const heading=(s:string)=>{page.drawText(s,{x:50,y,font:bold,size:13,color:rgb(.12,.23,.20)});y-=26};
 const block=(s:string)=>{for(const line of lines(s)){if(y<90)throw new Error("Draft too long for one page. Shorten the scope or terms.");page.drawText(line,{x:50,y,font,size:11,color:rgb(.15,.2,.18)});y-=18}y-=17};
 page.drawText("DRAFT - NOT AN INVOICE OR ACCEPTED OFFER",{x:50,y,font:bold,size:12,color:rgb(.5,.18,.16)});y-=48;
 heading("Build With Abhinav / Quote draft");block(`Prepared for: ${person.trim()}`);heading("Proposed scope");block(scope.trim());heading("Proposed total");block(`${currency} ${amount} - check tax, fees and any applicable charges before sending.`);heading("Validity, milestones and exclusions");block(terms.trim());
 page.drawText("Review recipient, scope, tax, total and terms before sharing. Nothing is sent by this tool.",{x:50,y:55,font,size:9,color:rgb(.35,.4,.38)});
 const data=await pdf.save();const url=URL.createObjectURL(new Blob([new Uint8Array(data)],{type:"application/pdf"}));const a=document.createElement("a");a.href=url;a.download="quote-draft.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
 }catch(e){setError(e instanceof Error?e.message:"PDF could not be created")}finally{setBusy(false)}}
 return <><h1>Quote draft (PDF)</h1><p className="page-sub">Make a private draft for your review. No client receives it, no invoice is issued, and it does not set a final price.</p><div className="admin-panel"><label className="admin-field"><span>Recipient or organization</span><input maxLength={120} value={person} onChange={e=>setPerson(e.target.value)}/></label><label className="admin-field"><span>Proposed scope</span><textarea rows={6} maxLength={1700} value={scope} onChange={e=>setScope(e.target.value)}/></label><div className="admin-row2"><label className="admin-field"><span>Currency</span><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>INR</option><option>USD</option><option>GBP</option><option>EUR</option></select></label><label className="admin-field"><span>Proposed total</span><input inputMode="decimal" maxLength={12} value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><label className="admin-field"><span>Validity, milestones and exclusions</span><textarea rows={4} maxLength={1200} value={terms} onChange={e=>setTerms(e.target.value)}/></label><p className="hint">This draft is created in your browser. Check taxes, recipient and facts before sharing it yourself.</p><button className="admin-btn" type="button" onClick={download} disabled={busy}>{busy?"Making draft…":"Download draft PDF"}</button><p role="alert">{error}</p></div></>
}
