"use client";
import {useEffect,useState} from "react";
type Referral={id:string;reference:string;note:string;stage:"idea"|"contacted"|"qualified"|"closed";createdAt:number};
const stages=["idea","contacted","qualified","closed"] as const;
export default function ReferralNotes(){const [items,setItems]=useState<Referral[]|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/admin/referrals",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load");setItems(d.referrals)}).catch(e=>setStatus(e.message))},[]);
 function patch(fn:(draft:Referral[])=>void){setItems(old=>{const copy=old?.map(x=>({...x}))||[];fn(copy);return copy});setStatus("")}
 async function save(){if(!items)return;setBusy(true);try{const r=await fetch("/api/admin/referrals",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({referrals:items})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save");setStatus("Saved privately. No offer is published or applied.")}catch(e){setStatus(e instanceof Error?e.message:"Could not save")}finally{setBusy(false)}}
 return <><h1>Referral notes</h1><p className="page-sub">Private lead tracking only. No reward, discount, signup link or referral terms are active. Agree the rules with the owner before any public offer.</p><div className="admin-panel">{items?.map((r,i)=><div className="content-editor-item" key={r.id}><div className="ce-head"><b>Referral note {i+1}</b><button type="button" className="admin-btn danger small" onClick={()=>patch(a=>a.splice(i,1))}>Remove</button></div><label className="admin-field"><span>Private reference (avoid sensitive details)</span><input maxLength={100} value={r.reference} onChange={e=>patch(a=>{a[i].reference=e.target.value})}/></label><label className="admin-field"><span>Stage</span><select value={r.stage} onChange={e=>patch(a=>{a[i].stage=e.target.value as Referral["stage"]})}>{stages.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label className="admin-field"><span>Private note</span><textarea maxLength={1000} value={r.note} onChange={e=>patch(a=>{a[i].note=e.target.value})}/></label></div>)}<button type="button" className="admin-btn secondary small" disabled={!items||items.length>=100} onClick={()=>patch(a=>a.push({id:crypto.randomUUID(),reference:"",note:"",stage:"idea",createdAt:Date.now()}))}>+ Add private note</button><div style={{marginTop:20}}><button type="button" className="admin-btn" disabled={!items||busy} onClick={save}>{busy?"Saving…":"Save notes"}</button> <span role="status">{status}</span></div></div></>;
}
