"use client";
import {useCallback,useEffect,useState} from "react";
type Review={id:string;ts:number;name:string;email:string;project:string;quote:string;consent:boolean};
export default function ReviewModeration(){const [items,setItems]=useState<Review[]|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{try{const res=await fetch("/api/admin/reviews",{cache:"no-store"});const body=await res.json();if(!res.ok)throw new Error(body.error||"Could not load submissions");setItems(body.reviews)}catch(e){setStatus(e instanceof Error?e.message:"Could not load submissions")}},[]);
 useEffect(()=>{load()},[load]);
 async function remove(id:string){if(!confirm("Delete this pending review? This cannot be undone."))return;setBusy(id);setStatus("");try{const res=await fetch("/api/admin/reviews",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Could not delete review");setStatus("Pending review deleted");await load()}catch(e){setStatus(e instanceof Error?e.message:"Could not delete review")}finally{setBusy("")}}
 return <><h1>Review submissions</h1><p className="page-sub">Private submissions awaiting your judgment. Nothing publishes automatically. Verify the person and their permission before copying any quote into Site content.</p><p role="status" className="hint">{status}</p><div className="admin-panel">{items===null?<p>Loading…</p>:items.length===0?<p>No pending reviews.</p>:items.map(r=><article className="inq-item" key={r.id}><h2>{r.name} · {r.project}</h2><p className="hint">{r.email} · {new Date(r.ts).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})} · Consent marked: {r.consent?"Yes":"No"}</p><p className="inq-msg">{r.quote}</p><button className="admin-btn danger small" type="button" disabled={busy===r.id} onClick={()=>remove(r.id)}>{busy===r.id?"Deleting…":"Delete pending review"}</button></article>)}</div></>;
}
