"use client";
import {useEffect,useState} from "react";
import {initializeApp,getApps} from "firebase/app";
import {getAuth,GoogleAuthProvider,signInWithPopup,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signInWithCustomToken,signOut,type Auth} from "firebase/auth";
type Config={apiKey:string;authDomain:string;projectId:string;appId:string};

function tone(){try{const C=window.AudioContext;const ctx=new C();const oscillator=ctx.createOscillator(),volume=ctx.createGain();oscillator.type="sine";oscillator.frequency.setValueAtTime(660,ctx.currentTime);oscillator.frequency.exponentialRampToValueAtTime(880,ctx.currentTime+.12);volume.gain.setValueAtTime(.035,ctx.currentTime);volume.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);oscillator.connect(volume);volume.connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+.2);setTimeout(()=>ctx.close(),350)}catch{}}
export default function ClientAuth({onAuthenticated}:{onAuthenticated:()=>Promise<void>}){const [config,setConfig]=useState<Config|null>(null),[auth,setAuth]=useState<Auth|null>(null),[mode,setMode]=useState<"signin"|"signup"|"email-code"|"reset">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[codeSent,setCodeSent]=useState(false),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[sound,setSound]=useState(false);
 useEffect(()=>{let mounted=true;fetch("/api/client/account-session",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(!mounted||!d.configured||!d.config)return;const app=getApps().find(a=>a.name==="buildcredit")||initializeApp(d.config,"buildcredit");setConfig(d.config);setAuth(getAuth(app))}).catch(()=>{});return()=>{mounted=false}},[]);
 async function finish(user:import("firebase/auth").User){await user.reload();const current=auth?.currentUser||user;if(!current.emailVerified){try{await sendEmailVerification(current)}catch{}setStatus("Check your inbox to verify your email, then sign in again.");await signOut(auth!);return}const idToken=await current.getIdToken(true);const r=await fetch("/api/client/account-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken})});const d=await r.json();if(!r.ok){setStatus(d.error||"Could not start your account session.");await signOut(auth!);return}if(sound)tone();setPassword("");setStatus("");await onAuthenticated()}
 async function submit(e:React.FormEvent){e.preventDefault();if(!auth||busy)return;setBusy(true);setStatus("");try{if(mode==="reset"){await sendPasswordResetEmail(auth,email.trim());setStatus("If an account exists, check that inbox for a reset link.");return}if(mode==="email-code"){const r=await fetch("/api/client/email-code",{method:codeSent?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.trim(),code})});const d=await r.json();if(!r.ok){setStatus(d.error||"Could not verify email code.");return}if(!codeSent){setStatus("A 6-digit code was sent to your email. Check your inbox.");setCodeSent(true);return}setCode("");setCodeSent(false);const result=await signInWithCustomToken(auth,d.customToken);await finish(result.user);return}const user=mode==="signup"?await createUserWithEmailAndPassword(auth,email.trim(),password):await signInWithEmailAndPassword(auth,email.trim(),password);await finish(user.user)}catch(error){const code=(error as {code?:string}).code||"";setStatus(code==="auth/email-already-in-use"?"That email already has an account. Sign in or reset your password.":code==="auth/weak-password"?"Choose a stronger password.":"Could not sign in. Check your details or try another method.")}finally{setBusy(false)}}
 async function google(){if(!auth||busy)return;setBusy(true);setStatus("");try{const user=await signInWithPopup(auth,new GoogleAuthProvider());await finish(user.user)}catch(error){const code=(error as {code?:string}).code||"";setStatus(code==="auth/popup-closed-by-user"?"Google sign-in was closed.":code==="auth/account-exists-with-different-credential"?"An account already exists with this email. Sign in with the original method before linking Google.":"Google sign-in could not finish. Try again.")}finally{setBusy(false)}}
 return <section className="auth-card"><div className="auth-brand"><img src="/images/abhinav.jpg" alt="Abhinav Kumar" width="58" height="58"/><span>Build Credit<br/><small>Private client access</small></span></div><h2>{mode==="signup"?"Create your account":mode==="reset"?"Reset your password":mode==="email-code"?"Email sign-in code": "Welcome back"}</h2><p>Sign in to your account. Your project and credits appear only after the owner links this account to your verified client record.</p>{!config?<p role="status">New account sign-in is not available yet. You can still use an owner-issued access code below.</p>:<><button type="button" className="auth-google" disabled={busy} onClick={google}>Continue with Google</button><div className="auth-divider">or use email</div><form onSubmit={submit}><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode==="email-code"&&codeSent&&<label>6-digit code<input required inputMode="numeric" pattern="[0-9]{6}" placeholder="123456" value={code.trim()} onChange={e=>setCode(e.target.value.slice(0,6))}/></label>}{(mode==="signin"||mode==="signup")&&<label>Password<input required minLength={6} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button disabled={busy} type="submit">{busy?"Please wait…":mode==="reset"?"Send reset link":mode==="email-code"?(codeSent?"Verify email code":"Send email code"):mode==="signup"?"Create account":"Sign in"}</button></form><div className="auth-options"><button type="button" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setStatus("")}}>{mode==="signin"?"New here? Sign up":"Back to sign in"}</button><button type="button" onClick={()=>{setMode("email-code");setCode("");setCodeSent(false)}}>Email code</button><button type="button" onClick={()=>setMode("reset")}>Forgot password?</button></div><label className="auth-sound"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> Play a soft sound after sign-in</label><p className="auth-note">Phone OTP is unavailable while free SMS delivery is not configured. No payment is made on this site.</p></>}{status&&<p role="status" className="auth-status">{status}</p>}</section>
}
