"use client";
import {useEffect,useState} from "react";
const softTone=()=>{try{const ctx=new window.AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.setValueAtTime(660,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(880,ctx.currentTime+.12);g.gain.setValueAtTime(.03,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.2);setTimeout(()=>ctx.close(),350)}catch{}};
type Mode="signin"|"signup"|"email-code"|"reset";
export default function ClientAuth({onAuthenticated}:{onAuthenticated:()=>Promise<void>}){const [configured,setConfigured]=useState(false),[mode,setMode]=useState<Mode>("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[code,setCode]=useState(""),[codeSent,setCodeSent]=useState(false),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[sound,setSound]=useState(false);
 useEffect(()=>{fetch("/api/client/account-session",{cache:"no-store"}).then(r=>r.json()).then(d=>setConfigured(Boolean(d.configured))).catch(()=>{})},[]);
 const switchMode=(m:Mode)=>{setMode(m);setCode("");setCodeSent(false);setStatus("")};
 async function submit(e:React.FormEvent){e.preventDefault();if(!configured||busy)return;setBusy(true);setStatus("");try{if(mode==="signin"){const r=await fetch("/api/client/account-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not sign in");if(sound)softTone();setPassword("");await onAuthenticated();return}if(mode==="reset"||mode==="signup"||mode==="email-code"){if(!codeSent){const r=await fetch("/api/client/email-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not send code");setCodeSent(true);setStatus("A 6-digit code has been sent to your email. It expires in 10 minutes.");return}const r=await fetch("/api/client/email-code",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code,...(mode==="signup"||mode==="reset"?{password,name}: {})})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not verify code");if(sound)softTone();setPassword("");setCode("");setCodeSent(false);await onAuthenticated()}}catch(e){setStatus(e instanceof Error?e.message:"Could not continue") }finally{setBusy(false)}}
 return <section className="auth-card"><div className="auth-brand"><img src="/images/abhinav.jpg" alt="Abhinav Kumar" width="58" height="58"/><span>Build Credit<br/><small>Private client access</small></span></div><h2>{mode==="signup"?"Create your account":mode==="reset"?"Reset your password":mode==="email-code"?"Sign in with email code":"Welcome back"}</h2><p>Your project and credits appear only after the owner links this verified account to your client record.</p>{!configured?<p role="status">Account sign-in is not ready yet. You can still use an owner-issued access code below.</p>:<><form onSubmit={submit}>{mode==="signup"&&<label>Your name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} autoComplete="name"/></label>}<label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{(mode==="signup"||mode==="signin"||mode==="reset")&&<label>{mode==="reset"?"New password":"Password"}<input required minLength={mode==="signin"?1:10} type="password" autoComplete={mode==="signin"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{codeSent&&<label>6-digit email code<input required inputMode="numeric" pattern="[0-9]{6}" placeholder="123456" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))}/></label>}<button type="submit" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":codeSent?mode==="reset"?"Verify and change password":mode==="signup"?"Verify and create account":"Verify and sign in":"Send email code"}</button></form><div className="auth-options"><button type="button" onClick={()=>switchMode(mode==="signup"?"signin":"signup")}>{mode==="signup"?"Back to sign in":"Sign up"}</button><button type="button" onClick={()=>switchMode("email-code")}>Email code</button><button type="button" onClick={()=>switchMode("reset")}>Forgot password?</button></div><label className="auth-sound"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> Play a soft sound after sign-in</label><p className="auth-note">Google sign-in and phone OTP are not available yet. No payment is made on this site.</p></>}{status&&<p role="status" className="auth-status">{status}</p>}</section>
}
