import Link from "next/link";
import InquiryForm from "./InquiryForm";
import WorkBrowser from "./WorkBrowser";
import JournalBrowser from "./JournalBrowser";
import ShareLink from "./ShareLink";
import Comparison from "./Comparison";
import { SiteChrome } from "./SiteChrome";
import { CtaBand, Eyebrow, PageIntro, ProjectCard, ServiceCard } from "./SiteParts";
import type { SiteContent, ChatbotSettings } from "../../lib/content";

export default function ContentPage({ kind, content, chatbot, region = "OTHER" }: { kind: "home" | "about" | "work" | "services" | "blog" | "contact" | "faq"; content: SiteContent; chatbot: ChatbotSettings; region?: string }) {
  return <SiteChrome chatbot={chatbot} announcement={content.announcement}>
    {kind === "home" && <main>
      <section className="v2-hero v2-container"><div className="v2-hero-copy"><Eyebrow n="01">INDEPENDENT CREATIVE DEVELOPER</Eyebrow><h1>Ideas into<br/><span>impact</span><i>.</i></h1><p>I build <strong>{content.hero.roleA}</strong> and <strong>{content.hero.roleB}</strong> that work. {content.hero.sub}</p><div className="v2-hero-actions"><Link href="/work" className="v2-button">Explore my work <span>↗</span></Link><Link href="/contact#demo" className="v2-text-link">Request a demo →</Link></div></div><div className="v2-hero-art"><div className="v2-orbit v2-orbit-one"/><div className="v2-orbit v2-orbit-two"/><img className="v2-portrait" src="/images/abhinav.jpg" alt="Portrait of Abhinav Kumar"/><span className="v2-art-label">DESIGN / CODE / AUTOMATE</span><span className="v2-art-stamp">BUILD WITH<br/>ABHINAV</span></div><div className="v2-hero-bottom"><span>Scroll to explore ↓</span><span>Web &amp; automation / India</span></div></section>
      <div className="v2-ticker"><div>CREATIVE DEVELOPMENT ✳ AI AUTOMATION ✳ DIGITAL EXPERIENCES ✳ SYSTEMS THAT WORK ✳ CREATIVE DEVELOPMENT ✳ AI AUTOMATION ✳</div></div>
      <section className="v2-section v2-container"><div className="v2-section-head"><div><Eyebrow n="02">SELECTED WORK</Eyebrow><h2>Proof is in<br/><em>the building.</em></h2></div><Link href="/work" className="v2-text-link">All projects ↗</Link></div><div className="v2-project-grid">{content.projects.slice(0, 2).map((p, i) => <ProjectCard project={p} index={i} key={p.name}/>)}</div></section>
      <section className="v2-section v2-container v2-home-services"><div className="v2-section-head"><div><Eyebrow n="03">WHAT I DO</Eyebrow><h2>Good ideas need<br/><em>good systems.</em></h2></div><Link href="/services" className="v2-text-link">All services ↗</Link></div><div className="v2-service-grid">{content.services.slice(0, 3).map((s,i)=><ServiceCard service={s} index={i} key={s.title}/>)}</div></section><CtaBand/></main>}
    {kind === "about" && <main><PageIntro n="01" label="ABOUT" title="A little about me." description="I am a student builder making digital products and systems with a bias for useful, clear results."/><section className="v2-section v2-container v2-about-layout"><div className="v2-about-mark">a<span>.</span></div><div><Eyebrow n="01">THE APPROACH</Eyebrow><h2>Curious by default.<br/><em>Builder by choice.</em></h2><p>I turn rough ideas into working websites and automations. My process is simple: understand the problem, build the smallest useful thing, and make it better with feedback.</p><p>The code and experiments behind my work are open to explore. I share projects and the thinking behind them as I learn.</p><Link href="/work" className="v2-text-link">Explore the work ↗</Link></div></section><section className="v2-section v2-container"><Eyebrow n="02">HOW I WORK</Eyebrow><div className="v2-process-grid">{content.process.map((s,i)=><article key={s.n}><span>0{i+1}</span><h3>{s.t}</h3><p>{s.d}</p></article>)}</div></section><CtaBand/></main>}
    {kind === "work" && <main><PageIntro n="01" label="SELECTED PROJECTS" title="Made, not imagined." description="A selection of builds and experiments. Explore the source for each project."/><section className="v2-section v2-container"><WorkBrowser projects={content.projects}/><ShareLink/></section><CtaBand/></main>}
    {kind === "services" && <main><PageIntro n="01" label="WHAT I DO" title="Practical, by design." description="Websites, workflows and digital tools tailored to the problem, not a template."/><section className="v2-section v2-container"><div className="v2-service-grid">{content.services.map((s,i)=><ServiceCard key={s.title+i} service={s} index={i}/>)}</div></section><section className="v2-section v2-container"><Eyebrow n="02">SAMPLE STARTING POINTS</Eyebrow><h2>Plans to start<br/><em>the conversation.</em></h2><p className="v2-disclaimer">Illustrative starting prices only. Final scope and quote are agreed before any work begins.</p><div className="v2-package-grid">{content.packages.filter(p=>p.published).map(p=><article className="v2-package" key={p.name}><span>{p.name}</span><h3><small className="v2-from">Starting from </small>{p.regionalPrices?.[region] || p.regionalPrices?.OTHER || p.price}</h3><p>{p.description}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><Link href="/contact">Discuss this option ↗</Link></article>)}</div></section><Comparison packages={content.packages.filter(p=>p.published)} region={region}/>{content.testimonials.some(t=>t.published) && <section className="v2-section v2-container"><Eyebrow n="03">WORDS FROM CLIENTS</Eyebrow><div className="v2-testimonials">{content.testimonials.filter(t=>t.published).map((t,i)=><blockquote key={i}><p>“{t.quote}”</p><footer>{t.name} {t.role && `· ${t.role}`}</footer></blockquote>)}</div></section>}<CtaBand/></main>}
    {kind === "blog" && <main><PageIntro n="01" label="JOURNAL" title="Notes from the build." description="Ideas, process notes and experiments from the workbench."/><section className="v2-section v2-container"><JournalBrowser posts={content.posts.filter(p=>p.published)}/></section><CtaBand/></main>}
    {kind === "faq" && <main><PageIntro n="01" label="QUESTIONS" title="The useful details." description="Answers to common questions about the work and how to get started."/><section className="v2-section v2-container v2-faq-list">{content.faqs.filter(f=>f.published).map((f,i)=><details key={i}><summary><span>{String(i+1).padStart(2,"0")} / {f.question}</span><span>+</span></summary><p>{f.answer}</p></details>)}</section><CtaBand/></main>}
    {kind === "contact" && <main><PageIntro n="01" label="GET IN TOUCH" title="Start with a conversation." description="Tell me what you have in mind. No long brief needed to begin."/><section className="v2-section v2-container v2-contact-grid"><div><Eyebrow n="02">PROJECT INQUIRY</Eyebrow><h2>Your idea,<br/><em>let&apos;s hear it.</em></h2><p>Share your goal, timeline and what a good result would look like. This form sends an inquiry, not a booking or a quote.</p><a className="v2-text-link" href="mailto:a83017083@gmail.com">Or send an email ↗</a><div className="v2-demo" id="demo"><Eyebrow n="03">DEMO CALL</Eyebrow><h3>Want to see how it works?</h3>{content.demoUrl ? <><p>Pick an available time through the calendar page.</p><a className="v2-button" href={content.demoUrl} target="_blank" rel="noopener noreferrer">Book a demo call ↗</a></> : <><p>Select &quot;Demo call request&quot; in the form. I&apos;ll reply to arrange a time; this does not reserve a slot yet.</p><a className="v2-text-link" href="#inquiry">Request in the form ↓</a></>}</div></div><div id="inquiry" className="v2-form-card"><InquiryForm/></div></section></main>}
  </SiteChrome>;
}
