"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import type {SearchEntry} from "../../lib/search-entries";
const pages=[{label:"Home",href:"/",words:"portfolio websites automations"},{label:"About",href:"/about",words:"builder process"},{label:"Work",href:"/work",words:"projects github case studies"},{label:"Stack",href:"/stack",words:"technology skills"},{label:"Services",href:"/services",words:"pricing packages websites automation"},{label:"Journal",href:"/blog",words:"blog notes"},{label:"FAQ",href:"/faq",words:"questions answers"},{label:"Contact",href:"/contact",words:"demo call inquiry email"},{label:"Resources",href:"/resources",words:"free templates checklist worksheet"}];
type Recognition={lang:string;interimResults:boolean;maxAlternatives:number;onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
type SpeechWindow=Window & {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export default function SiteSearch({entries}:{entries:SearchEntry[]}){
 const[open,setOpen]=useState(false),[query,setQuery]=useState(""),[speaking,setSpeaking]=useState(false),[voiceAvailable,setVoiceAvailable]=useState(false),[voiceError,setVoiceError]=useState("");
 const inputRef=useRef<HTMLInputElement>(null),triggerRef=useRef<HTMLButtonElement>(null),recognitionRef=useRef<Recognition|null>(null),seenOpen=useRef(false);
 useEffect(()=>{const w=window as SpeechWindow;setVoiceAvailable(Boolean(w.SpeechRecognition||w.webkitSpeechRecognition))},[]);
 useEffect(()=>{if(open){inputRef.current?.focus();seenOpen.current=true}else{recognitionRef.current?.stop();recognitionRef.current=null;setSpeaking(false);if(seenOpen.current)triggerRef.current?.focus()}},[open]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setOpen(x=>!x)}if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 function voice(){if(speaking){recognitionRef.current?.stop();return}const w=window as SpeechWindow;const Ctor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Ctor){setVoiceError("Voice search is not available here. Type to search instead.");return}
  const r=new Ctor();recognitionRef.current=r;r.lang=navigator.language||"en-IN";r.interimResults=false;r.maxAlternatives=1;
  r.onresult=e=>{const text=e.results[0]?.[0]?.transcript?.trim();if(text){setQuery(text);setVoiceError("");inputRef.current?.focus()}};
  r.onerror=e=>{setVoiceError(e.error==="not-allowed"?"Microphone access was not allowed. Type to search instead.":"Voice search stopped. Type to search instead.")};
  r.onend=()=>{setSpeaking(false);recognitionRef.current=null};try{r.start();setSpeaking(true);setVoiceError("")}catch{setSpeaking(false);setVoiceError("Could not start voice search. Type to search instead.")}
 }
 const results=query.trim()?[...pages,...entries].filter(p=>`${p.label} ${p.words}`.toLowerCase().includes(query.toLowerCase())).slice(0,15):pages;
 return <><button ref={triggerRef} className="v2-search-btn" aria-label="Search site" onClick={()=>setOpen(true)}>⌕ <span>Search</span> <kbd>⌘K</kbd></button>{open&&<div className="v2-search-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}} onKeyDown={e=>{if(e.key!=="Tab")return;const panel=e.currentTarget.querySelector(".v2-search-panel");const focusables=Array.from(panel?.querySelectorAll<HTMLElement>("input,button,a[href]")||[]);const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}} role="dialog" aria-modal="true" aria-label="Site search"><div className="v2-search-panel"><div className="v2-search-controls"><input ref={inputRef} type="search" placeholder="Search pages, projects and notes…" value={query} onChange={e=>setQuery(e.target.value)}/>{voiceAvailable&&<button type="button" onClick={voice} aria-label={speaking?"Stop voice search":"Start voice search"} aria-pressed={speaking} title={speaking?"Stop listening":"Search by voice"}>{speaking?"■":"🎙"}</button>}<button type="button" onClick={()=>setOpen(false)} aria-label="Close search">×</button></div>{speaking&&<p role="status" className="v2-search-voice-status">Listening. Speak a search term, or press Stop.</p>}{voiceError&&<p role="status" className="v2-search-voice-status">{voiceError}</p>}<div>{results.map((r,i)=><Link href={r.href} key={`${r.label}-${i}`} onClick={()=>{setOpen(false);setQuery("")}}>{r.label}<span>↗</span></Link>)}{results.length===0&&<p>No match. Try another word.</p>}</div></div></div>}</>;
}
