import crypto from "crypto";
import {cookies} from "next/headers";
import {kvReadResult,kvCreateEmailAccount,kvSetEmailPassword} from "./kv";
export const ACCOUNTS_KEY="client:auth:accounts:v1";
export type AuthAccount={uid:string;email:string;name:string;createdAt:number;clientId?:string|null;disabled?:boolean;passwordHash?:string};
export const normalizeEmail=(input:unknown)=>typeof input==="string"?input.trim().toLowerCase():"";
export const emailOk=(email:string)=>email.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
export const emailCodeKey=(email:string)=>`client:email-code:${crypto.createHash("sha256").update(email).digest("hex")}`;
export function hashEmailCode(email:string,code:string){return crypto.createHmac("sha256",process.env.ADMIN_PASSWORD||"").update(email+":"+code).digest("hex")}
export function authConfigured(){return Boolean(process.env.ADMIN_PASSWORD&&process.env.REDIS_URL||process.env.ADMIN_PASSWORD&&process.env.KV_REST_API_URL&&process.env.KV_REST_API_TOKEN)&&Boolean(process.env.GMAIL_USER&&process.env.GMAIL_APP_PASSWORD)}
export async function readAuthAccounts(){const result=await kvReadResult<AuthAccount[]>(ACCOUNTS_KEY);return {ok:result.ok&&(result.value===null||Array.isArray(result.value)),accounts:Array.isArray(result.value)?result.value:[]}}
export function hashPassword(password:string){const salt=crypto.randomBytes(16).toString("hex");const hash=crypto.scryptSync(password,salt,64).toString("hex");return `scrypt:${salt}:${hash}`}
export function verifyPassword(password:string,stored:string){const [kind,salt,hash]=stored.split(":");if(kind!=="scrypt"||!salt||!hash||!/^[a-f0-9]{32}$/.test(salt)||!/^[a-f0-9]{128}$/.test(hash))return false;const a=crypto.scryptSync(password,salt,64),b=Buffer.from(hash,"hex");return crypto.timingSafeEqual(a,b)}
export async function createVerifiedAccount(email:string,name=""){const record:AuthAccount={uid:crypto.randomUUID(),email,name:name.trim().slice(0,100)||email.split("@")[0],createdAt:Date.now()};const saved=await kvCreateEmailAccount(ACCOUNTS_KEY,record,500);if(saved===null)return {ok:false,error:"Storage unavailable"};if(!saved)return {ok:false,error:"Account limit reached"};const accounts=await readAuthAccounts();if(!accounts.ok)return {ok:false,error:"Storage unavailable"};return {ok:true,account:accounts.accounts.find(a=>a.email===email)} as const}
export async function updatePassword(uid:string,hash:string){return kvSetEmailPassword(ACCOUNTS_KEY,uid,hash)}
function secret(){return process.env.ADMIN_PASSWORD||""}
export function makeAccountCookie(uid:string,passwordHash=""){const credential=crypto.createHash("sha256").update(passwordHash).digest("hex").slice(0,16);const payload=Buffer.from(JSON.stringify({uid,credential,exp:Date.now()+86400000})).toString("base64url");const signature=crypto.createHmac("sha256",secret()).update(payload).digest("base64url");return `${payload}.${signature}`}
export async function currentAuthAccount(){const raw=cookies().get("portfolio_account")?.value;if(!raw||!secret())return null;const [payload,sig]=raw.split(".");if(!payload||!sig)return null;const expected=crypto.createHmac("sha256",secret()).update(payload).digest("base64url");const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const d=JSON.parse(Buffer.from(payload,"base64url").toString());if(!d.uid||!Number.isFinite(d.exp)||d.exp<Date.now())return null;const accounts=await readAuthAccounts();if(!accounts.ok)return null;return accounts.accounts.find(a=>a.uid===d.uid&&!a.disabled&&d.credential===crypto.createHash("sha256").update(a.passwordHash||"").digest("hex").slice(0,16))||null}catch{return null}}
