import {NextResponse} from "next/server";
import crypto from "crypto";
import nodemailer from "nodemailer";
import {firebaseAdmin,authConfigured} from "../../../../lib/client-auth";
import {kvRateLimit,kvSetExpiring,kvConsumeEmailCode} from "../../../../lib/kv";
const origin="https://buildweth-abhinavk7852.vercel.app";
const normalize=(v:unknown)=>typeof v==="string"?v.trim().toLowerCase():"";
const emailOk=(x:string)=>x.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x);
const key=(email:string)=>`client:email-code:${crypto.createHash("sha256").update(email).digest("hex")}`;
const hash=(email:string,code:string)=>crypto.createHmac("sha256",process.env.ADMIN_PASSWORD||"").update(email+":"+code).digest("hex");
const noStore={"Cache-Control":"private, no-store"};
export async function POST(req:Request){if(!authConfigured()||!process.env.GMAIL_USER||!process.env.GMAIL_APP_PASSWORD||!process.env.ADMIN_PASSWORD)return NextResponse.json({error:"Email sign-in not configured"},{status:503});const b=await req.json().catch(()=>null);const email=normalize(b?.email);if(!emailOk(email))return NextResponse.json({error:"Enter a valid email"},{status:400});const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const id=crypto.createHash("sha256").update(ip).digest("hex");const [allowedIp,allowedEmail]=await Promise.all([kvRateLimit(`client:otp:ip:${id}`,10,3600),kvRateLimit(`client:otp:mail:${key(email)}`,3,3600)]);if(allowedIp===null||allowedEmail===null)return NextResponse.json({error:"Sign-in storage unavailable"},{status:503});if(!allowedIp||!allowedEmail)return NextResponse.json({error:"Too many code requests. Try later."},{status:429});const code=String(crypto.randomInt(0,1_000_000)).padStart(6,"0");const transport=nodemailer.createTransport({host:"smtp.gmail.com",port:465,secure:true,auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_APP_PASSWORD}});if(!await kvSetExpiring(key(email),{hash:hash(email,code)},600))return NextResponse.json({error:"Could not secure the code. Try later."},{status:503});try{await transport.sendMail({from:`"Build With Abhinav" <${process.env.GMAIL_USER}>`,to:email,subject:"Your Build Credit sign-in code",text:`Your Build Credit sign-in code is ${code}. It expires in 10 minutes. If you did not request it, ignore this email.\n\n${origin}/client`})}catch{return NextResponse.json({error:"Could not send the code. Try again later."},{status:503})}return NextResponse.json({ok:true},{headers:noStore})}
export async function PUT(req:Request){if(!authConfigured()||!process.env.ADMIN_PASSWORD)return NextResponse.json({error:"Email sign-in not configured"},{status:503});const b=await req.json().catch(()=>null);const email=normalize(b?.email),code=b?.code;if(!emailOk(email)||typeof code!=="string"||!/^\d{6}$/.test(code))return NextResponse.json({error:"Invalid code"},{status:400});const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const attempts=await kvRateLimit(`client:otp:verify:${crypto.createHash("sha256").update(ip+email).digest("hex")}`,8,900);if(attempts===null)return NextResponse.json({error:"Sign-in storage unavailable"},{status:503});if(!attempts)return NextResponse.json({error:"Too many attempts. Request a new code later."},{status:429});const matched=await kvConsumeEmailCode(key(email),hash(email,code));if(matched===null)return NextResponse.json({error:"Sign-in storage unavailable"},{status:503});if(!matched)return NextResponse.json({error:"Code incorrect or expired"},{status:401});const admin=firebaseAdmin();if(!admin)return NextResponse.json({error:"Auth unavailable"},{status:503});let user;try{user=await admin.getUserByEmail(email);if(user.disabled)return NextResponse.json({error:"This account is disabled"},{status:403});if(!user.emailVerified)await admin.updateUser(user.uid,{emailVerified:true})}catch(e){if((e as {code?:string}).code!=="auth/user-not-found")return NextResponse.json({error:"Account lookup unavailable"},{status:503});user=await admin.createUser({email,emailVerified:true})}try{const token=await admin.createCustomToken(user.uid);return NextResponse.json({customToken:token},{headers:noStore})}catch{return NextResponse.json({error:"Could not complete sign-in"},{status:503})}}
