import {NextResponse} from "next/server";
import crypto from "crypto";
import nodemailer from "nodemailer";
import {authConfigured,normalizeEmail,emailOk,emailCodeKey,hashEmailCode,readAuthAccounts,createVerifiedAccount,hashPassword,updatePassword} from "../../../../lib/client-auth";
import {kvRateLimit,kvSetExpiring,kvConsumeEmailCode} from "../../../../lib/kv";
import {makeAccountCookie} from "../../../../lib/client-auth";
const noStore={"Cache-Control":"private, no-store"};
export async function POST(req:Request){if(!authConfigured()||!process.env.GMAIL_USER||!process.env.GMAIL_APP_PASSWORD)return NextResponse.json({error:"Email sign-in not configured"},{status:503});const b=await req.json().catch(()=>null);const email=normalizeEmail(b?.email);if(!emailOk(email))return NextResponse.json({error:"Enter a valid email"},{status:400});const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const id=crypto.createHash("sha256").update(ip).digest("hex");const [ipAllowed,emailAllowed]=await Promise.all([kvRateLimit(`client:otp:ip:${id}`,10,3600),kvRateLimit(`client:otp:mail:${emailCodeKey(email)}`,3,3600)]);if(ipAllowed===null||emailAllowed===null)return NextResponse.json({error:"Storage unavailable"},{status:503});if(!ipAllowed||!emailAllowed)return NextResponse.json({error:"Too many code requests. Try later."},{status:429});const accounts=await readAuthAccounts();if(!accounts.ok)return NextResponse.json({error:"Storage unavailable"},{status:503});if(accounts.accounts.some(a=>a.email===email&&a.disabled))return NextResponse.json({error:"Account unavailable"},{status:403});const code=String(crypto.randomInt(0,1_000_000)).padStart(6,"0");if(!await kvSetExpiring(emailCodeKey(email),{hash:hashEmailCode(email,code)},600))return NextResponse.json({error:"Storage unavailable"},{status:503});const transport=nodemailer.createTransport(!process.env.VERCEL&&process.env.TEST_SMTP_PORT?{host:"127.0.0.1",port:Number(process.env.TEST_SMTP_PORT),secure:false,tls:{rejectUnauthorized:false}}:{host:"smtp.gmail.com",port:465,secure:true,auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_APP_PASSWORD}});try{await transport.sendMail({from:`"Build With Abhinav" <${process.env.GMAIL_USER}>`,to:email,subject:"Your Build Credit sign-in code",text:`Your Build Credit sign-in code is ${code}. It expires in 10 minutes. If you did not request it, ignore this email.\n\nhttps://buildweth-abhinavk7852.vercel.app/client`})}catch(e){console.error("client email code send failed",e);return NextResponse.json({error:"Could not send the code. Try again later."},{status:503})}return NextResponse.json({ok:true},{headers:noStore})}
export async function PUT(req:Request){if(!authConfigured())return NextResponse.json({error:"Email sign-in not configured"},{status:503});const b=await req.json().catch(()=>null);const email=normalizeEmail(b?.email),code=b?.code,password=b?.password,name=b?.name;const settingPassword=typeof password==="string"&&password.length>0;if(!emailOk(email)||typeof code!=="string"||!/^\d{6}$/.test(code)||settingPassword&&(password.length<10||password.length>256)||name!==undefined&&(typeof name!=="string"||name.length>100))return NextResponse.json({error:"Invalid code or password"},{status:400});const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const attempts=await kvRateLimit(`client:otp:verify:${crypto.createHash("sha256").update(ip+email).digest("hex")}`,8,900);if(attempts===null)return NextResponse.json({error:"Storage unavailable"},{status:503});if(!attempts)return NextResponse.json({error:"Too many attempts. Request a new code later."},{status:429});const matched=await kvConsumeEmailCode(emailCodeKey(email),hashEmailCode(email,code));if(matched===null)return NextResponse.json({error:"Storage unavailable"},{status:503});if(!matched)return NextResponse.json({error:"Code incorrect or expired"},{status:401});const created=await createVerifiedAccount(email,typeof name==="string"?name:"");if(!created.ok||!created.account)return NextResponse.json({error:created.error||"Could not create account"},{status:503});if(settingPassword){const saved=await updatePassword(created.account.uid,hashPassword(password));if(!saved)return NextResponse.json({error:"Could not save password"},{status:503})}const uid=created.account.uid;const updated=settingPassword?await readAuthAccounts():null;if(updated&&!updated.ok)return NextResponse.json({error:"Storage unavailable"},{status:503});const account=updated?updated.accounts.find(a=>a.uid===uid):created.account;if(!account)return NextResponse.json({error:"Account unavailable"},{status:503});const r=NextResponse.json({ok:true},{headers:noStore});r.cookies.set("portfolio_account",makeAccountCookie(account.uid,account.passwordHash||""),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:86400});return r}
