import {NextResponse} from "next/server";
import crypto from "crypto";
import {authConfigured,readAuthAccounts,currentAuthAccount,makeAccountCookie,normalizeEmail,emailOk,verifyPassword} from "../../../../lib/client-auth";
import {readClients} from "../../../../lib/client-portal";
import {kvRateLimit} from "../../../../lib/kv";
const noStore={"Cache-Control":"private, no-store"};
function session(uid:string,passwordHash:string){const r=NextResponse.json({ok:true},{headers:noStore});r.cookies.set("portfolio_account",makeAccountCookie(uid,passwordHash),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:86400});return r}
export async function GET(){if(!authConfigured())return NextResponse.json({configured:false},{headers:noStore});const account=await currentAuthAccount();if(!account)return NextResponse.json({configured:true,account:null},{headers:noStore});const clients=await readClients();if(!clients.ok)return NextResponse.json({error:"Storage unavailable"},{status:503});const linked=clients.clients.some(c=>c.id===account.clientId);return NextResponse.json({configured:true,account:{email:account.email,name:account.name,linked}},{headers:noStore})}
export async function POST(req:Request){if(!authConfigured())return NextResponse.json({error:"Login not configured"},{status:503});const b=await req.json().catch(()=>null);const email=normalizeEmail(b?.email),password=b?.password;if(!emailOk(email)||typeof password!=="string"||password.length>256)return NextResponse.json({error:"Invalid credentials"},{status:400});const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const attempts=await kvRateLimit(`client:password:attempt:${crypto.createHash("sha256").update(ip+email).digest("hex")}`,12,900);if(attempts===null)return NextResponse.json({error:"Storage unavailable"},{status:503});if(!attempts)return NextResponse.json({error:"Too many attempts. Try later."},{status:429});const accounts=await readAuthAccounts();if(!accounts.ok)return NextResponse.json({error:"Storage unavailable"},{status:503});const a=accounts.accounts.find(a=>a.email===email&&!a.disabled);if(!a?.passwordHash||!verifyPassword(password,a.passwordHash))return NextResponse.json({error:"Incorrect email or password"},{status:401});return session(a.uid,a.passwordHash)}
export async function DELETE(){const r=NextResponse.json({ok:true},{headers:noStore});r.cookies.set("portfolio_account","",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:0});return r}
