import {NextResponse} from "next/server";
import {isAuthed} from "../../../../lib/admin-guard";
import {ACCOUNTS_KEY,authConfigured,readAuthAccounts} from "../../../../lib/client-auth";
import {readClients} from "../../../../lib/client-portal";
import {kvSetAuthClient,kvDisableAuthAccount} from "../../../../lib/kv";
import {audit} from "../../../../lib/audit";
export async function GET(){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});const [accounts,clients]=await Promise.all([readAuthAccounts(),readClients()]);if(!accounts.ok||!clients.ok)return NextResponse.json({error:"Storage unavailable"},{status:503});return NextResponse.json({configured:authConfigured(),accounts:accounts.accounts.map(({passwordHash,...a})=>a),clients:clients.clients.map(c=>({id:c.id,name:c.name,project:c.project}))},{headers:{"Cache-Control":"private, no-store"}})}
export async function PATCH(req:Request){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>null);if(!b||typeof b.uid!=="string"||b.uid.length>200||typeof b.clientId!=="string")return NextResponse.json({error:"Bad request"},{status:400});const [accounts,clients]=await Promise.all([readAuthAccounts(),readClients()]);if(!accounts.ok||!clients.ok)return NextResponse.json({error:"Storage unavailable"},{status:503});const a=accounts.accounts.find(a=>a.uid===b.uid&&!a.disabled);if(!a)return NextResponse.json({error:"Account not found"},{status:404});if(b.clientId&&!clients.clients.some(c=>c.id===b.clientId))return NextResponse.json({error:"Client record not found"},{status:404});if(b.clientId&&accounts.accounts.some(x=>x.uid!==b.uid&&!x.disabled&&x.clientId===b.clientId))return NextResponse.json({error:"Client record already linked"},{status:409});const saved=await kvSetAuthClient(ACCOUNTS_KEY,b.uid,b.clientId||null);if(saved===null)return NextResponse.json({error:"Storage unavailable"},{status:503});if(!saved)return NextResponse.json({error:"Account not found or client already linked"},{status:409});await audit("account-link",`Auth account ${b.uid.slice(0,8)} ${b.clientId?"linked":"unlinked"}`);return NextResponse.json({ok:true})}
export async function DELETE(req:Request){if(!isAuthed())return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>null);if(typeof b?.uid!=="string"||b.uid.length>200)return NextResponse.json({error:"Bad request"},{status:400});const saved=await kvDisableAuthAccount(ACCOUNTS_KEY,b.uid);if(saved===null)return NextResponse.json({error:"Storage unavailable"},{status:503});if(!saved)return NextResponse.json({error:"Account not found"},{status:404});await audit("account-disabled",`Auth account ${b.uid.slice(0,8)} disabled`);return NextResponse.json({ok:true})}
